# Generated by Django 4.1.7 on 2023-04-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanrouting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaninfo',
            name='institute_name',
            field=models.CharField(default='w', max_length=60),
            preserve_default=False,
        ),
    ]
