# Generated by Django 4.1.7 on 2023-04-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vanrouting', '0005_vaninfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaninfo',
            name='image',
        ),
    ]
