# Generated by Django 4.1.7 on 2023-04-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vanrouting', '0007_vaninfo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutes_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=60)),
                ('institute_address', models.CharField(max_length=80)),
                ('institute_image', models.ImageField(upload_to='images')),
                ('institute_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vaninfo',
            name='institute_name',
        ),
        migrations.AddField(
            model_name='vaninfo',
            name='Institutes_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vanrouting.institutes_details'),
            preserve_default=False,
        ),
    ]
